"""empty message

Revision ID: 15647043195d
Revises: ac9a28d4c00a
Create Date: 2026-10-06 14:15:47.320168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15647043195d'
down_revision = 'ac9a28d4c00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
