"""empty message

Revision ID: 2343445b75d0
Revises: 4107b4f86d4b
Create Date: 2026-09-25 16:02:52.368999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2343445b75d0'
down_revision = '4107b4f86d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('specialty_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('specialty_id'), ['specialty_id'], unique=True)

    # ### end Alembic commands ###
