"""empty message

Revision ID: 5102f229862b
Revises: 36dd492481a8
Create Date: 2026-09-25 12:43:33.093599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5102f229862b'
down_revision = '36dd492481a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Enum('Not available', 'Available'), nullable=False),
    sa.Column('licence_number', sa.String(length=100), nullable=False),
    sa.Column('consultation_fee', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('specialty_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###
