"""empty message

Revision ID: 68da395c7b9d
Revises: 15647043195d
Create Date: 2026-10-06 14:16:39.189090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68da395c7b9d'
down_revision = '15647043195d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
