"""empty message

Revision ID: 80200772f5bf
Revises: 85dcea892cd6
Create Date: 2026-10-05 14:03:15.055674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80200772f5bf'
down_revision = '85dcea892cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Accepted', 'Rejected', 'Cancelled', 'Completed'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_fee', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('consultation_fee')

    op.drop_table('appointments')
    # ### end Alembic commands ###
